# Form implementation generated from reading ui file 'comparar.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pruebaF1 as f1


class Ui_wComparar(object):
    def setupUi(self, wComparar):
        wComparar.setObjectName("wComparar")
        wComparar.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(wComparar)
        self.centralwidget.setObjectName("centralwidget")
        self.listPilotos = QtWidgets.QListWidget(self.centralwidget)
        self.listPilotos.setGeometry(QtCore.QRect(100, 200, 401, 192))
        self.listPilotos.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.listPilotos.setObjectName("listPilotos")
        self.tGranPremio = QtWidgets.QLineEdit(self.centralwidget)
        self.tGranPremio.setGeometry(QtCore.QRect(100, 80, 241, 31))
        self.tGranPremio.setObjectName("tGranPremio")
        self.bBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.bBuscar.setGeometry(QtCore.QRect(380, 100, 111, 41))
        self.bBuscar.setObjectName("bBuscar")
        self.lGranPremio = QtWidgets.QLabel(self.centralwidget)
        self.lGranPremio.setGeometry(QtCore.QRect(100, 60, 141, 16))
        self.lGranPremio.setObjectName("lGranPremio")
        self.bComparar = QtWidgets.QPushButton(self.centralwidget)
        self.bComparar.setGeometry(QtCore.QRect(100, 420, 401, 41))
        self.bComparar.setObjectName("bComparar")
        self.tAnio = QtWidgets.QLineEdit(self.centralwidget)
        self.tAnio.setGeometry(QtCore.QRect(100, 140, 241, 31))
        self.tAnio.setObjectName("tAnio")
        self.lAnio = QtWidgets.QLabel(self.centralwidget)
        self.lAnio.setGeometry(QtCore.QRect(100, 120, 60, 16))
        self.lAnio.setObjectName("lAnio")
        wComparar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wComparar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        wComparar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wComparar)
        self.statusbar.setObjectName("statusbar")
        wComparar.setStatusBar(self.statusbar)

        self.retranslateUi(wComparar)
        QtCore.QMetaObject.connectSlotsByName(wComparar)
        self.bBuscar.clicked.connect(self.click_buscar)
        self.bComparar.clicked.connect(self.click_comparar)

    def click_buscar(self):
        drivers=f1.cargarGP(self.tGranPremio.text(),self.tAnio.text())
        for d in drivers:
            self.listPilotos.addItem(d)
    def click_comparar(self):
        pilotos=[]
        for p in self.listPilotos.selectedItems():
            pilotos.append(p.text())
        f1.compararPilotos(self.tGranPremio.text(),self.tAnio.text(),pilotos)
        print(self.listPilotos.selectedItems())
    def retranslateUi(self, wComparar):
        _translate = QtCore.QCoreApplication.translate
        wComparar.setWindowTitle(_translate("wComparar", "MainWindow"))
        self.bBuscar.setText(_translate("wComparar", "Buscar"))
        self.lGranPremio.setText(_translate("wComparar", "Introducir Gran Premio"))
        self.bComparar.setText(_translate("wComparar", "Comparar Pilotos"))
        self.lAnio.setText(_translate("wComparar", "Año"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wComparar = QtWidgets.QMainWindow()
    ui = Ui_wComparar()
    ui.setupUi(wComparar)
    wComparar.show()
    sys.exit(app.exec())
