# Form implementation generated from reading ui file 'desgloseVuelta.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pruebaF1 as f1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tGranPremio = QtWidgets.QLineEdit(self.centralwidget)
        self.tGranPremio.setGeometry(QtCore.QRect(30, 60, 191, 21))
        self.tGranPremio.setObjectName("tGranPremio")
        self.tAnio = QtWidgets.QLineEdit(self.centralwidget)
        self.tAnio.setGeometry(QtCore.QRect(30, 120, 191, 21))
        self.tAnio.setObjectName("tAnio")
        self.lGranPremio = QtWidgets.QLabel(self.centralwidget)
        self.lGranPremio.setGeometry(QtCore.QRect(30, 40, 81, 16))
        self.lGranPremio.setObjectName("lGranPremio")
        self.lAnio = QtWidgets.QLabel(self.centralwidget)
        self.lAnio.setGeometry(QtCore.QRect(30, 100, 60, 16))
        self.lAnio.setObjectName("lAnio")
        self.bBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.bBuscar.setGeometry(QtCore.QRect(250, 80, 211, 32))
        self.bBuscar.setObjectName("bBuscar")
        self.listaPilotos = QtWidgets.QListWidget(self.centralwidget)
        self.listaPilotos.setGeometry(QtCore.QRect(30, 180, 191, 301))
        self.listaPilotos.setObjectName("listaPilotos")
        self.bBuscar2 = QtWidgets.QPushButton(self.centralwidget)
        self.bBuscar2.setGeometry(QtCore.QRect(30, 500, 211, 32))
        self.bBuscar2.setObjectName("bBuscar2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.bBuscar.clicked.connect(self.click_buscar)
        self.bBuscar2.clicked.connect(self.click_desglosar)

    def click_buscar(self):
        drivers=f1.cargarGP(self.tGranPremio.text(),self.tAnio.text())
        for d in drivers:
            self.listaPilotos.addItem(d)
    def click_desglosar(self):
        piloto=""
        for p in self.listaPilotos.selectedItems():
            piloto=p.text()
        f1.desgloseTelemetria(self.tGranPremio.text(),self.tAnio.text(), piloto)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lGranPremio.setText(_translate("MainWindow", "Gran Premio"))
        self.lAnio.setText(_translate("MainWindow", "Año"))
        self.bBuscar.setText(_translate("MainWindow", "Buscar"))
        self.bBuscar2.setText(_translate("MainWindow", "Desglosar vueltas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
