# Form implementation generated from reading ui file 'vueltaRapida.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pruebaF1 as f1


class Ui_wResultadosQualy(object):
    def setupUi(self, wResultadosQualy):
        wResultadosQualy.setObjectName("wResultadosQualy")
        wResultadosQualy.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(wResultadosQualy)
        self.centralwidget.setObjectName("centralwidget")
        self.tGranPremio = QtWidgets.QLineEdit(self.centralwidget)
        self.tGranPremio.setGeometry(QtCore.QRect(40, 50, 281, 21))
        self.tGranPremio.setObjectName("tGranPremio")
        self.lGranPremio = QtWidgets.QLabel(self.centralwidget)
        self.lGranPremio.setGeometry(QtCore.QRect(40, 20, 121, 16))
        self.lGranPremio.setObjectName("lGranPremio")
        self.bVuelta = QtWidgets.QPushButton(self.centralwidget)
        self.bVuelta.setGeometry(QtCore.QRect(350, 70, 191, 41))
        self.bVuelta.setObjectName("bVuelta")
        self.tAnio = QtWidgets.QLineEdit(self.centralwidget)
        self.tAnio.setGeometry(QtCore.QRect(40, 105, 281, 21))
        self.tAnio.setObjectName("tAnio")
        self.lAnio = QtWidgets.QLabel(self.centralwidget)
        self.lAnio.setGeometry(QtCore.QRect(40, 85, 60, 16))
        self.lAnio.setObjectName("lAnio")
        wResultadosQualy.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wResultadosQualy)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        wResultadosQualy.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wResultadosQualy)
        self.statusbar.setObjectName("statusbar")
        wResultadosQualy.setStatusBar(self.statusbar)

        self.retranslateUi(wResultadosQualy)
        QtCore.QMetaObject.connectSlotsByName(wResultadosQualy)
        self.bVuelta.clicked.connect(self.obtenVuelta)
    def obtenVuelta(self):
        f1.resultadosQualy(self.tGranPremio.text(),self.tAnio.text())
    def retranslateUi(self, wResultadosQualy):
        _translate = QtCore.QCoreApplication.translate
        wResultadosQualy.setWindowTitle(_translate("wResultadosQualy", "MainWindow"))
        self.lGranPremio.setText(_translate("wResultadosQualy", "Gran Premio"))
        self.bVuelta.setText(_translate("wResultadosQualy", "Ver resultados qualy"))
        self.lAnio.setText(_translate("wComparar", "Año"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wResultadosQualy = QtWidgets.QMainWindow()
    ui = Ui_wResultadosQualy()
    ui.setupUi(wResultadosQualy)
    wResultadosQualy.show()
    sys.exit(app.exec())
