# Form implementation generated from reading ui file 'telemetria.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('Qt5Agg')
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as Navi
from matplotlib.figure import Figure
from Listas import años
import pruebaF1 as f1


class MatplotlibCanvas(FigureCanvasQTAgg):
    def __init__(self,parent=None, dpi = 120):
        fig = Figure(dpi = dpi)
        self.axes = fig.add_subplot(111)
        super(MatplotlibCanvas,self).__init__(fig)
        fig.tight_layout()

class Ui_wAnios(object):
    def setupUi(self, wAnios):
        wAnios.setObjectName("wAnios")
        wAnios.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(wAnios)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 441, 121))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(20, 50, 320, 49))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.bAnio = QtWidgets.QComboBox(self.widget)
        self.bAnio.setObjectName("bAnio")
        self.gridLayout.addWidget(self.bAnio, 1, 0, 1, 1)
        self.bCircuito = QtWidgets.QComboBox(self.widget)
        self.bCircuito.setObjectName("bCircuito")
        self.gridLayout.addWidget(self.bCircuito, 1, 1, 1, 1)
        self.bPiloto = QtWidgets.QComboBox(self.widget)
        self.bPiloto.setObjectName("bPiloto")
        self.gridLayout.addWidget(self.bPiloto, 1, 2, 1, 1)
        self.w1 = QtWidgets.QWidget(self.centralwidget)
        self.w1.setGeometry(QtCore.QRect(20, 170, 761, 191))
        self.w1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.w1.setObjectName("w1")
        self.w2 = QtWidgets.QWidget(self.centralwidget)
        self.w2.setGeometry(QtCore.QRect(20, 370, 761, 191))
        self.w2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.w2.setObjectName("w2")
        self.w3 = QtWidgets.QWidget(self.centralwidget)
        self.w3.setGeometry(QtCore.QRect(20, 570, 761, 191))
        self.w3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.w3.setObjectName("w3")
        wAnios.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(wAnios)
        self.statusbar.setObjectName("statusbar")
        wAnios.setStatusBar(self.statusbar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.canv = MatplotlibCanvas(self)
        self.gridLayout.addWidget(self.canv)

        self.retranslateUi(wAnios)
        QtCore.QMetaObject.connectSlotsByName(wAnios)
        self.bAnio.addItems(años)
        self.bAnio.currentTextChanged.connect(self.addCircuitos)
        self.bAnio.setCurrentIndex(-1)

        self.bCircuito.activated.connect(self.cargarSesion)

        self.bPiloto.activated.connect(self.actualizarPlot)

        


    def actualizarPlot(self):
        f1.desgloseTelemetria(self.bCircuito.currentText(),self.bAnio.currentText(),self.bPiloto.currentText())
        #self.ax = self.canv.figure.subplots()
        
        #self.bar = None
        #self.ax.plot(telemetry['Distance'], telemetry['Throttle'], label=self.bPiloto.currentText())
        #self.canv.draw()

    def cargarSesion(self):
        if(self.bCircuito.currentText()!=""):
            pilotos=f1.cargarGP(self.bCircuito.currentText(),self.bAnio.currentText())
            self.bPiloto.clear()
            self.bPiloto.addItems(pilotos)
            self.bPiloto.setCurrentIndex(-1)

    def addCircuitos(self):
        año= self.bAnio.currentText()
        self.bCircuito.clear()
        if año=="2018":
            from Listas import circuitos1
            self.bCircuito.addItems(circuitos1)
            self.bCircuito.setCurrentIndex(-1)
        if año=="2019":
            from Listas import circuitos2
            self.bCircuito.addItems(circuitos2)
            self.bCircuito.setCurrentIndex(-1)
        if año=="2020":
            from Listas import circuitos3
            self.bCircuito.addItems(circuitos3)
            self.bCircuito.setCurrentIndex(-1)
        if año=="2021":
            from Listas import circuitos4
            self.bCircuito.addItems(circuitos4)
            self.bCircuito.setCurrentIndex(-1)

    def retranslateUi(self, wAnios):
        _translate = QtCore.QCoreApplication.translate
        wAnios.setWindowTitle(_translate("wAnios", "Telemetria"))
        self.groupBox.setTitle(_translate("wAnios", "Parametros"))
        self.label.setText(_translate("wAnios", "Año"))
        self.label_2.setText(_translate("wAnios", "Circuito"))
        self.label_3.setText(_translate("wAnios", "Piloto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wAnios = QtWidgets.QMainWindow()
    ui = Ui_wAnios()
    ui.setupUi(wAnios)
    wAnios.show()
    sys.exit(app.exec())
