# Form implementation generated from reading ui file 'vueltaRapida.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pruebaF1 as f1


class Ui_wVueltaRapida(object):
    def setupUi(self, wVueltaRapida):
        wVueltaRapida.setObjectName("wVueltaRapida")
        wVueltaRapida.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(wVueltaRapida)
        self.centralwidget.setObjectName("centralwidget")
        self.tGranPremio = QtWidgets.QLineEdit(self.centralwidget)
        self.tGranPremio.setGeometry(QtCore.QRect(40, 50, 281, 21))
        self.tGranPremio.setObjectName("tGranPremio")
        self.lGranPremio = QtWidgets.QLabel(self.centralwidget)
        self.lGranPremio.setGeometry(QtCore.QRect(40, 20, 121, 16))
        self.lGranPremio.setObjectName("lGranPremio")
        self.bVuelta = QtWidgets.QPushButton(self.centralwidget)
        self.bVuelta.setGeometry(QtCore.QRect(350, 70, 191, 41))
        self.bVuelta.setObjectName("bVuelta")
        self.lTexto = QtWidgets.QLabel(self.centralwidget)
        self.lTexto.setGeometry(QtCore.QRect(40, 150, 581, 181))
        self.lTexto.setText("")
        self.lTexto.setObjectName("lTexto")
        self.tAnio = QtWidgets.QLineEdit(self.centralwidget)
        self.tAnio.setGeometry(QtCore.QRect(40, 105, 281, 21))
        self.tAnio.setObjectName("tAnio")
        self.lAnio = QtWidgets.QLabel(self.centralwidget)
        self.lAnio.setGeometry(QtCore.QRect(40, 85, 60, 16))
        self.lAnio.setObjectName("lAnio")
        wVueltaRapida.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wVueltaRapida)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        wVueltaRapida.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wVueltaRapida)
        self.statusbar.setObjectName("statusbar")
        wVueltaRapida.setStatusBar(self.statusbar)

        self.retranslateUi(wVueltaRapida)
        QtCore.QMetaObject.connectSlotsByName(wVueltaRapida)
        self.bVuelta.clicked.connect(self.obtenVuelta)
    def obtenVuelta(self):
        tiempo, piloto=f1.vueltasRapidas(self.tGranPremio.text(),self.tAnio.text())
        self.lTexto.setText("la vuelta rapida del circuito la tiene "+ piloto)
        self.lTexto.setText(self.lTexto.text() +" y es de " +str(tiempo))
        f1.marchasVuelta(self.tGranPremio.text(),self.tAnio.text())
    def retranslateUi(self, wVueltaRapida):
        _translate = QtCore.QCoreApplication.translate
        wVueltaRapida.setWindowTitle(_translate("wVueltaRapida", "MainWindow"))
        self.lGranPremio.setText(_translate("wVueltaRapida", "Gran Premio"))
        self.bVuelta.setText(_translate("wVueltaRapida", "Buscar Vuelta Rapida"))
        self.lAnio.setText(_translate("wComparar", "Año"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wVueltaRapida = QtWidgets.QMainWindow()
    ui = Ui_wVueltaRapida()
    ui.setupUi(wVueltaRapida)
    wVueltaRapida.show()
    sys.exit(app.exec())
